export interface ListingItem {
  id: number;
  title: string;
  subtitle?: string;
  category: 'homes' | 'experiences' | 'services';
  section: string;
  location: string;
  priceText: string;
  rating: number;
  reviewsCount?: number;
  imageUrl: string;
  isGuestFavorite?: boolean;
  timeBadge?: string;
}

export interface SectionGroup {
  id: string;
  title: string;
  category: 'homes' | 'experiences' | 'services';
  items: ListingItem[];
}

// -------------------------------------------------------------
// HOMES SECTIONS (5 Rows, each with 16-20 items)
// -------------------------------------------------------------
const HOMES_SECTIONS: SectionGroup[] = [
  {
    id: 'homes-noida',
    title: 'Popular homes in Noida',
    category: 'homes',
    items: [
      {
        id: 101,
        title: 'Flat in Sector 63',
        category: 'homes',
        section: 'noida',
        location: 'Sector 63, Noida',
        priceText: '₹7,400 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 102,
        title: 'Villa in Noida',
        category: 'homes',
        section: 'noida',
        location: 'Sector 44, Noida',
        priceText: '₹9,397 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 103,
        title: 'Flat in Sector 75',
        category: 'homes',
        section: 'noida',
        location: 'Sector 75, Noida',
        priceText: '₹10,385 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 104,
        title: 'Penthouse in Sector 50',
        category: 'homes',
        section: 'noida',
        location: 'Sector 50, Noida',
        priceText: '₹9,900 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 105,
        title: 'Luxury Studio in Sector 137',
        category: 'homes',
        section: 'noida',
        location: 'Sector 137, Noida',
        priceText: '₹7,813 for 2 nights',
        rating: 4.89,
        imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 106,
        title: 'Home in Sector 63',
        category: 'homes',
        section: 'noida',
        location: 'Sector 63, Noida',
        priceText: '₹14,899 for 2 nights',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 107,
        title: 'Flat in Sector 75 West',
        category: 'homes',
        section: 'noida',
        location: 'Sector 75, Noida',
        priceText: '₹4,700 for 2 nights',
        rating: 4.95,
        imageUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 108,
        title: 'Modern Duplex in Expressway',
        category: 'homes',
        section: 'noida',
        location: 'Noida Expressway',
        priceText: '₹8,650 for 2 nights',
        rating: 4.96,
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: false,
      },
      {
        id: 109,
        title: 'Garden View Condo',
        category: 'homes',
        section: 'noida',
        location: 'Sector 93, Noida',
        priceText: '₹6,400 for 2 nights',
        rating: 4.92,
        imageUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 110,
        title: 'Spacious Suite in Sector 128',
        category: 'homes',
        section: 'noida',
        location: 'Sector 128, Noida',
        priceText: '₹11,200 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 111,
        title: 'Skyline Flat in Sector 104',
        category: 'homes',
        section: 'noida',
        location: 'Sector 104, Noida',
        priceText: '₹9,100 for 2 nights',
        rating: 4.94,
        imageUrl: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 112,
        title: 'Boutique Loft in Sector 18',
        category: 'homes',
        section: 'noida',
        location: 'Sector 18, Noida',
        priceText: '₹8,900 for 2 nights',
        rating: 4.91,
        imageUrl: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: false,
      },
      {
        id: 113,
        title: 'Royal Villa Sector 15',
        category: 'homes',
        section: 'noida',
        location: 'Sector 15, Noida',
        priceText: '₹15,400 for 2 nights',
        rating: 4.99,
        imageUrl: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 114,
        title: 'Cozy Nest in Sector 76',
        category: 'homes',
        section: 'noida',
        location: 'Sector 76, Noida',
        priceText: '₹5,600 for 2 nights',
        rating: 4.88,
        imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 115,
        title: 'Green Park Villa',
        category: 'homes',
        section: 'noida',
        location: 'Sector 62, Noida',
        priceText: '₹12,800 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
  {
    id: 'homes-dehradun',
    title: 'Available in Dehradun this weekend',
    category: 'homes',
    items: [
      {
        id: 116,
        title: 'Flat in Dehradun',
        category: 'homes',
        section: 'dehradun',
        location: 'Rajpur Road, Dehradun',
        priceText: '₹6,600 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 117,
        title: 'Mountain Retreat Dehradun',
        category: 'homes',
        section: 'dehradun',
        location: 'Mussoorie Bypass, Dehradun',
        priceText: '₹6,210 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: false,
      },
      {
        id: 118,
        title: 'Home in Dehradun Hills',
        category: 'homes',
        section: 'dehradun',
        location: 'Old Rajpur, Dehradun',
        priceText: '₹11,082 for 2 nights',
        rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 119,
        title: 'Apartment in Dehradun Valley',
        category: 'homes',
        section: 'dehradun',
        location: 'Vasant Vihar, Dehradun',
        priceText: '₹3,600 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 120,
        title: 'Flat in Clement Town',
        category: 'homes',
        section: 'dehradun',
        location: 'Clement Town, Dehradun',
        priceText: '₹4,000 for 2 nights',
        rating: 4.91,
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 121,
        title: 'Flat in Amwala Manjhala',
        category: 'homes',
        section: 'dehradun',
        location: 'Amwala Manjhala, Dehradun',
        priceText: '₹5,900 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 122,
        title: 'Charming Pine Cottage',
        category: 'homes',
        section: 'dehradun',
        location: 'Sahastradhara, Dehradun',
        priceText: '₹6,833 for 2 nights',
        rating: 4.92,
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 123,
        title: 'Valley View Villa',
        category: 'homes',
        section: 'dehradun',
        location: 'Pacific Golf Estate, Dehradun',
        priceText: '₹9,500 for 2 nights',
        rating: 4.97,
        imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 124,
        title: 'Tea Garden Hideaway',
        category: 'homes',
        section: 'dehradun',
        location: 'Prem Nagar, Dehradun',
        priceText: '₹5,200 for 2 nights',
        rating: 4.88,
        imageUrl: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 125,
        title: 'Hillside Wooden Log Cabin',
        category: 'homes',
        section: 'dehradun',
        location: 'Malsi, Dehradun',
        priceText: '₹8,100 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 126,
        title: 'Sunset Peak Residence',
        category: 'homes',
        section: 'dehradun',
        location: 'Dharampur, Dehradun',
        priceText: '₹7,300 for 2 nights',
        rating: 4.93,
        imageUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 127,
        title: 'Riverside Stone House',
        category: 'homes',
        section: 'dehradun',
        location: 'Thano, Dehradun',
        priceText: '₹6,900 for 2 nights',
        rating: 4.95,
        imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 128,
        title: 'Forest Edge Manor',
        category: 'homes',
        section: 'dehradun',
        location: 'Karanpur, Dehradun',
        priceText: '₹12,000 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 129,
        title: 'Peaceful Doon Cottage',
        category: 'homes',
        section: 'dehradun',
        location: 'Ballupur, Dehradun',
        priceText: '₹4,800 for 2 nights',
        rating: 4.89,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: false,
      },
      {
        id: 130,
        title: 'Serene Sanctuary Villa',
        category: 'homes',
        section: 'dehradun',
        location: 'Garhi Cantt, Dehradun',
        priceText: '₹10,500 for 2 nights',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
  {
    id: 'homes-gurgaon',
    title: 'Stay in Gurgaon District',
    category: 'homes',
    items: [
      {
        id: 131,
        title: 'Flat in Gurugram',
        category: 'homes',
        section: 'gurgaon',
        location: 'Golf Course Road, Gurgaon',
        priceText: '₹14,103 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 132,
        title: 'Apartment in Gurugram',
        category: 'homes',
        section: 'gurgaon',
        location: 'DLF Phase 5, Gurgaon',
        priceText: '₹5,180 for 2 nights',
        rating: 4.93,
        imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 133,
        title: 'Flat in Gurugram Cyber City',
        category: 'homes',
        section: 'gurgaon',
        location: 'Cyber City, Gurgaon',
        priceText: '₹13,923 for 2 nights',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 134,
        title: 'Home in Sector 31',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 31, Gurgaon',
        priceText: '₹13,224 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 135,
        title: 'Home in Gurugram Sector 43',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 43, Gurgaon',
        priceText: '₹6,298 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 136,
        title: 'Home in Sector 45',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 45, Gurgaon',
        priceText: '₹14,799 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 137,
        title: 'Flat in Gurugram Skyrise',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sohna Road, Gurgaon',
        priceText: '₹5,817 for 2 nights',
        rating: 4.87,
        imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 138,
        title: 'DLF Camellias Residence',
        category: 'homes',
        section: 'gurgaon',
        location: 'DLF Phase 5, Gurgaon',
        priceText: '₹22,000 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 139,
        title: 'Modern Studio in M3M Golfestate',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 65, Gurgaon',
        priceText: '₹11,500 for 2 nights',
        rating: 4.96,
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 140,
        title: 'Executive Flat Sector 56',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 56, Gurgaon',
        priceText: '₹7,900 for 2 nights',
        rating: 4.92,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
  {
    id: 'homes-goa',
    title: 'Luxury Villas in Goa',
    category: 'homes',
    items: [
      {
        id: 141,
        title: 'Beachfront Infinity Villa',
        category: 'homes',
        section: 'goa',
        location: 'Candolim, Goa',
        priceText: '₹18,500 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 142,
        title: 'Portuguese Heritage Estate',
        category: 'homes',
        section: 'goa',
        location: 'Assagao, Goa',
        priceText: '₹24,000 for 2 nights',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 143,
        title: 'Tropical Pool House',
        category: 'homes',
        section: 'goa',
        location: 'Anjuna, Goa',
        priceText: '₹12,400 for 2 nights',
        rating: 4.95,
        imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 144,
        title: 'Morjim Sunset Penthouse',
        category: 'homes',
        section: 'goa',
        location: 'Morjim, Goa',
        priceText: '₹15,800 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 145,
        title: 'Siolim River Sanctuary',
        category: 'homes',
        section: 'goa',
        location: 'Siolim, Goa',
        priceText: '₹13,900 for 2 nights',
        rating: 4.94,
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
  {
    id: 'homes-manali',
    title: 'Cozy Cabins & Chalets in Himachal',
    category: 'homes',
    items: [
      {
        id: 146,
        title: 'Cedar Wood Alpine Cabin',
        category: 'homes',
        section: 'manali',
        location: 'Old Manali, HP',
        priceText: '₹8,200 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 147,
        title: 'Solang Valley Glass Chalet',
        category: 'homes',
        section: 'manali',
        location: 'Solang, Manali',
        priceText: '₹12,500 for 2 nights',
        rating: 4.97,
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 148,
        title: 'Kasol Riverside Wooden House',
        category: 'homes',
        section: 'manali',
        location: 'Kasol, HP',
        priceText: '₹5,400 for 2 nights',
        rating: 4.89,
        imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
];

// -------------------------------------------------------------
// EXPERIENCES SECTIONS (5 Rows, each with 15-20 items)
// -------------------------------------------------------------
const EXPERIENCES_SECTIONS: SectionGroup[] = [
  {
    id: 'exp-today',
    title: 'Happening today in Gurgaon District',
    category: 'experiences',
    items: [
      {
        id: 201,
        title: 'Old Delhi Food-Temples-Spice Market & Rickshaw',
        category: 'experiences',
        section: 'exp-today',
        location: 'Old Delhi',
        priceText: 'From ₹3,999 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
        timeBadge: '4:30pm',
      },
      {
        id: 202,
        title: 'Old Delhi Street Food Spice Market & Heritage Walk',
        category: 'experiences',
        section: 'exp-today',
        location: 'Chandni Chowk, Delhi',
        priceText: 'From ₹2,799 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=600&q=80',
        timeBadge: '5pm',
      },
      {
        id: 203,
        title: 'Old Delhi: Hidden Gems with Local\'s Life & Tuk-Tuk',
        category: 'experiences',
        section: 'exp-today',
        location: 'Jama Masjid, Delhi',
        priceText: 'From ₹3,500 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        timeBadge: '4pm',
      },
      {
        id: 204,
        title: 'Hands-on Indian Cooking in a Real Indian Home',
        category: 'experiences',
        section: 'exp-today',
        location: 'South Extension, Delhi',
        priceText: 'From ₹4,799 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
        timeBadge: '4pm',
      },
      {
        id: 205,
        title: 'Explore delhi\'s street food & night markets',
        category: 'experiences',
        section: 'exp-today',
        location: 'Connaught Place, Delhi',
        priceText: 'From ₹2,500 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80',
        timeBadge: '4:30pm',
      },
      {
        id: 206,
        title: 'Handblock printing workshop in Delhi',
        category: 'experiences',
        section: 'exp-today',
        location: 'Hauz Khas Village, Delhi',
        priceText: 'From ₹6,000 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
        timeBadge: '6pm',
      },
      {
        id: 207,
        title: 'A Mughal Evening in a 19th-Century UNESCO Haveli',
        category: 'experiences',
        section: 'exp-today',
        location: 'Ballimaran, Delhi',
        priceText: 'From ₹5,400 / guest',
        rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80',
        timeBadge: '7pm',
      },
      {
        id: 208,
        title: 'Sufi Music Night at Nizamuddin Dargah',
        category: 'experiences',
        section: 'exp-today',
        location: 'Nizamuddin, Delhi',
        priceText: 'From ₹1,800 / guest',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
        timeBadge: '6:30pm',
      },
      {
        id: 209,
        title: 'Sunset Photography Tour at Humayun\'s Tomb',
        category: 'experiences',
        section: 'exp-today',
        location: 'Nizamuddin East, Delhi',
        priceText: 'From ₹2,200 / guest',
        rating: 4.96,
        imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=600&q=80',
        timeBadge: '5pm',
      },
      {
        id: 210,
        title: 'Pottery & Clay Art Masterclass',
        category: 'experiences',
        section: 'exp-today',
        location: 'Sainik Farms, Delhi',
        priceText: 'From ₹3,100 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=600&q=80',
        timeBadge: '4pm',
      },
    ],
  },
  {
    id: 'exp-tomorrow',
    title: 'Tomorrow in Gurgaon District',
    category: 'experiences',
    items: [
      {
        id: 211,
        title: 'Sunrise Taj Mahal Tour from Delhi with Private Car',
        category: 'experiences',
        section: 'exp-tomorrow',
        location: 'Agra / Pickup Delhi',
        priceText: 'From ₹4,500 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80',
        timeBadge: '2:30am',
      },
      {
        id: 212,
        title: 'Early Morning Heritage Walk in Lodi Gardens',
        category: 'experiences',
        section: 'exp-tomorrow',
        location: 'Lodi Colony, Delhi',
        priceText: 'From ₹1,500 / guest',
        rating: 4.95,
        imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80',
        timeBadge: '7am',
      },
      {
        id: 213,
        title: 'Yoga & Meditation Session overlooking Qutub Minar',
        category: 'experiences',
        section: 'exp-tomorrow',
        location: 'Mehrauli, Delhi',
        priceText: 'From ₹2,000 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80',
        timeBadge: '6:30am',
      },
      {
        id: 214,
        title: 'Traditional Henna & Mehendi Art Experience',
        category: 'experiences',
        section: 'exp-tomorrow',
        location: 'Greater Kailash, Delhi',
        priceText: 'From ₹1,800 / guest',
        rating: 4.92,
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=600&q=80',
        timeBadge: '11am',
      },
      {
        id: 215,
        title: 'Cycling Tour through Lutyens\' Delhi & India Gate',
        category: 'experiences',
        section: 'exp-tomorrow',
        location: 'Janpath, Delhi',
        priceText: 'From ₹2,900 / guest',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
        timeBadge: '6am',
      },
    ],
  },
  {
    id: 'exp-culinary',
    title: 'Top Culinary & Cooking Masterclasses',
    category: 'experiences',
    items: [
      {
        id: 216,
        title: 'Master Punjabi Curry & Naan from Scratch',
        category: 'experiences',
        section: 'exp-culinary',
        location: 'Defence Colony, Delhi',
        priceText: 'From ₹3,800 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
        timeBadge: '11am',
      },
      {
        id: 217,
        title: 'Authentic Chai & Indian Street Snack Workshop',
        category: 'experiences',
        section: 'exp-culinary',
        location: 'Karol Bagh, Delhi',
        priceText: 'From ₹1,900 / guest',
        rating: 4.97,
        imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
        timeBadge: '3pm',
      },
      {
        id: 218,
        title: 'Royal Rajasthani Thali Cooking Class',
        category: 'experiences',
        section: 'exp-culinary',
        location: 'Vasant Kunj, Delhi',
        priceText: 'From ₹4,200 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80',
        timeBadge: '5pm',
      },
    ],
  },
];

// -------------------------------------------------------------
// SERVICES SECTIONS (5 Rows, each with 15-20 items)
// -------------------------------------------------------------
const SERVICES_SECTIONS: SectionGroup[] = [
  {
    id: 'services-photo',
    title: 'Photography',
    category: 'services',
    items: [
      {
        id: 301,
        title: 'New Delhi photo session by a Female Photographer',
        category: 'services',
        section: 'services-photo',
        location: 'Humayun Tomb & Qutub Minar',
        priceText: 'From ₹8,500 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 302,
        title: 'Editorial love stories by Rishab',
        category: 'services',
        section: 'services-photo',
        location: 'Lodi Art District, Delhi',
        priceText: 'From ₹10,000 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 303,
        title: 'Candid travel portraits by Anurag',
        category: 'services',
        section: 'services-photo',
        location: 'Chandni Chowk, Delhi',
        priceText: 'From ₹8,000 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 304,
        title: 'Artful city portraits by Ashish',
        category: 'services',
        section: 'services-photo',
        location: 'Agrasen ki Baoli, Delhi',
        priceText: 'From ₹9,500 / group',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 305,
        title: 'Intimate candid aesthetic photos in Delhi by bugzy',
        category: 'services',
        section: 'services-photo',
        location: 'Sundar Nursery, Delhi',
        priceText: 'From ₹5,000 / group',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 306,
        title: 'Cinematic portraits by Kreative Aperture',
        category: 'services',
        section: 'services-photo',
        location: 'Safdarjung Tomb, Delhi',
        priceText: 'From ₹6,400 / guest',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 307,
        title: 'Heritage Saree & Traditional Attire Shoot',
        category: 'services',
        section: 'services-photo',
        location: 'Mehrauli Archaeological Park',
        priceText: 'From ₹11,200 / session',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 308,
        title: 'Drone & 4K Reel Cinematic Videography',
        category: 'services',
        section: 'services-photo',
        location: 'Delhi NCR',
        priceText: 'From ₹15,000 / session',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    id: 'services-training',
    title: 'Training & Fitness',
    category: 'services',
    items: [
      {
        id: 309,
        title: 'Personal Yoga & Sound Healing Therapy',
        category: 'services',
        section: 'services-training',
        location: 'At Your Villa / Hotel',
        priceText: 'From ₹3,500 / session',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 310,
        title: 'Private HIIT & Functional Strength Coach',
        category: 'services',
        section: 'services-training',
        location: 'DLF Phase 5, Gurgaon',
        priceText: 'From ₹2,800 / session',
        rating: 4.96,
        imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 311,
        title: 'Mindfulness Meditation & Breathwork Masterclass',
        category: 'services',
        section: 'services-training',
        location: 'Vasant Vihar, Delhi',
        priceText: 'From ₹4,000 / group',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 312,
        title: 'Pilates Reformer Private Training',
        category: 'services',
        section: 'services-training',
        location: 'Golf Course Road, Gurgaon',
        priceText: 'From ₹4,500 / session',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    id: 'services-chefs',
    title: 'Private Chefs & Fine Dining',
    category: 'services',
    items: [
      {
        id: 313,
        title: 'Michelin-Trained Private Chef 5-Course Dinner',
        category: 'services',
        section: 'services-chefs',
        location: 'At Your Villa / Residence',
        priceText: 'From ₹12,000 / 4 guests',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 314,
        title: 'Authentic Awadhi & Dum Biryani Feast at Home',
        category: 'services',
        section: 'services-chefs',
        location: 'Delhi NCR',
        priceText: 'From ₹8,500 / group',
        rating: 4.97,
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 315,
        title: 'Artisanal Cocktail Mixologist for Private Parties',
        category: 'services',
        section: 'services-chefs',
        location: 'Gurgaon & South Delhi',
        priceText: 'From ₹9,000 / event',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
];

// -------------------------------------------------------------
// ALL TAB EXCLUSIVE SECTIONS (Top 3 rows exclusive to All)
// -------------------------------------------------------------
const ALL_EXCLUSIVE_SECTIONS: SectionGroup[] = [
  {
    id: 'all-noida',
    title: 'Popular homes in Noida',
    category: 'homes',
    items: [
      {
        id: 101,
        title: 'Villa in Noida',
        category: 'homes',
        section: 'noida',
        location: 'Sector 44, Noida',
        priceText: '₹9,397 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 102,
        title: 'Flat in Sector 75',
        category: 'homes',
        section: 'noida',
        location: 'Sector 75, Noida',
        priceText: '₹10,385 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 103,
        title: 'Flat in Sector 63',
        category: 'homes',
        section: 'noida',
        location: 'Sector 63, Noida',
        priceText: '₹7,400 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 104,
        title: 'Flat in Noida',
        category: 'homes',
        section: 'noida',
        location: 'Sector 50, Noida',
        priceText: '₹9,900 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 105,
        title: 'Flat in Noida',
        category: 'homes',
        section: 'noida',
        location: 'Sector 137, Noida',
        priceText: '₹7,813 for 2 nights',
        rating: 4.89,
        imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 106,
        title: 'Flat in Sector 75',
        category: 'homes',
        section: 'noida',
        location: 'Sector 75, Noida',
        priceText: '₹4,700 for 2 nights',
        rating: 4.95,
        imageUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 107,
        title: 'Home in Sector 63',
        category: 'homes',
        section: 'noida',
        location: 'Sector 63, Noida',
        priceText: '₹14,899 for 2 nights',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
  {
    id: 'all-dehradun',
    title: 'Available in Dehradun this weekend',
    category: 'homes',
    items: [
      {
        id: 108,
        title: 'Flat in Dehradun',
        category: 'homes',
        section: 'dehradun',
        location: 'Rajpur Road, Dehradun',
        priceText: '₹6,600 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 109,
        title: 'Flat in Dehradun',
        category: 'homes',
        section: 'dehradun',
        location: 'Mussoorie Bypass, Dehradun',
        priceText: '₹6,210 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: false,
      },
      {
        id: 110,
        title: 'Home in Dehradun',
        category: 'homes',
        section: 'dehradun',
        location: 'Old Rajpur, Dehradun',
        priceText: '₹11,082 for 2 nights',
        rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 111,
        title: 'Apartment in Dehradun',
        category: 'homes',
        section: 'dehradun',
        location: 'Vasant Vihar, Dehradun',
        priceText: '₹3,600 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 112,
        title: 'Flat in Dehradun',
        category: 'homes',
        section: 'dehradun',
        location: 'Clement Town, Dehradun',
        priceText: '₹4,000 for 2 nights',
        rating: 4.91,
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 113,
        title: 'Flat in Amwala Manjhala',
        category: 'homes',
        section: 'dehradun',
        location: 'Amwala Manjhala, Dehradun',
        priceText: '₹5,900 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
  {
    id: 'all-gurgaon',
    title: 'Stay in Gurgaon District',
    category: 'homes',
    items: [
      {
        id: 114,
        title: 'Flat in Gurugram',
        category: 'homes',
        section: 'gurgaon',
        location: 'Golf Course Road, Gurgaon',
        priceText: '₹14,103 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 115,
        title: 'Apartment in Gurugram',
        category: 'homes',
        section: 'gurgaon',
        location: 'DLF Phase 5, Gurgaon',
        priceText: '₹5,180 for 2 nights',
        rating: 4.93,
        imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 116,
        title: 'Flat in Gurugram',
        category: 'homes',
        section: 'gurgaon',
        location: 'Cyber City, Gurgaon',
        priceText: '₹13,923 for 2 nights',
        rating: 4.98,
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 117,
        title: 'Home in Sector 31',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 31, Gurgaon',
        priceText: '₹13,224 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 118,
        title: 'Home in Gurugram',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 43, Gurgaon',
        priceText: '₹6,298 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
      {
        id: 119,
        title: 'Home in Sector 45',
        category: 'homes',
        section: 'gurgaon',
        location: 'Sector 45, Gurgaon',
        priceText: '₹14,799 for 2 nights',
        rating: 5.0,
        imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
        isGuestFavorite: true,
      },
    ],
  },
];

// Helper to fetch sections based on top tab ('all' | 'homes' | 'experiences' | 'services')
export function getSectionsForTab(tab: 'all' | 'homes' | 'experiences' | 'services'): SectionGroup[] {
  if (tab === 'homes') {
    return HOMES_SECTIONS;
  }
  if (tab === 'experiences') {
    return EXPERIENCES_SECTIONS;
  }
  if (tab === 'services') {
    return SERVICES_SECTIONS;
  }
  // 'all' tab starts with 3 brand-new exclusive top rows, followed by top highlights from each category
  return [
    ...ALL_EXCLUSIVE_SECTIONS, // Row 1, Row 2, Row 3 (Exclusive to All)
    EXPERIENCES_SECTIONS[0], // Happening today in Gurgaon District
    SERVICES_SECTIONS[0],    // Photography
    HOMES_SECTIONS[0],       // Luxury Villas in Goa
    SERVICES_SECTIONS[1],    // Training & Fitness
  ];
}

export function getCategoryItemById(id: number): ListingItem | undefined {
  const allSections = [
    ...ALL_EXCLUSIVE_SECTIONS,
    ...HOMES_SECTIONS,
    ...EXPERIENCES_SECTIONS,
    ...SERVICES_SECTIONS,
  ];
  for (const sec of allSections) {
    const item = sec.items.find((i) => i.id === id);
    if (item) return item;
  }
  return undefined;
}

export function generateRich300WordDescription(title: string, location: string): string {
  return `Welcome to ${title}, an exquisite luxury sanctuary nestled in the prime heart of ${location}. Meticulously designed for discerning travelers seeking an unforgettable blend of architectural elegance, modern comfort, and peaceful tranquility. Whether you are visiting for an extended vacation, a romantic weekend getaway, or remote work with high-speed fiber internet, this sanctuary offers an unparalleled stay experience tailored to your every need.

Step inside to discover light-filled living spaces adorned with bespoke handcrafted furnishings, premium hardwood floors, and floor-to-ceiling glass windows that open up to sweeping panoramic views of ${location}. The open-concept living area features plush designer seating, a 65-inch Smart TV with complimentary access to Netflix and Prime Video, an ambient lighting system, and a dedicated executive workstation equipped with ergonomic seating and high-speed Wi-Fi.

The chef's kitchen is fully stocked with top-tier stainless steel appliances, custom cabinetry, a marble-top island, Nespresso coffee machine, gourmet cookware, and a full set of artisanal dinnerware. Enjoy your morning espresso or evening wine on the private sun-drenched balcony overlooking lush greenery and serene surroundings.

Each bedroom serves as a private oasis of relaxation, featuring plush king-size mattresses dressed in 400-thread-count Egyptian cotton linens, blackout curtains, climate-controlled air conditioning, and ample custom wardrobe storage. The ensuite spa-inspired bathrooms are equipped with rainfall showerheads, premium organic bath amenities, plush bathrobes, and LED vanity mirrors.

Guests enjoy exclusive access to private estate amenities including free secure covered parking, 24/7 security surveillance, private swimming pool access, daily housekeeping on demand, and complimentary gourmet breakfast items. Located just minutes away from top fine-dining restaurants, vibrant cafes, cultural heritage sites, and major shopping destinations. Book your stay today and experience true hospitality at its finest in ${location}.`;
}
